baseurl = "https://heiber.im"
canonifyurls = true
copyright = "Licensed under CC-by-4.0"
editor = "vim"
enableGitInfo = true
languageCode = "en-us"
metaDataFormat = "toml"
paginate = 10
theme = "cactus"
title = "Moritz Heiber"

[author]
name = "Moritz Heiber"

[markup]
noClasses = false
[markup.highlight]
style = "monokai"

[minify.tdewolff.html]
keepWhitespace = true

[params]
colorTheme = "dark"
css = ["css/custom.css"]
description = "Hi, I'm Moritz. My purpose in life seems to be trying to outsmart computers. I'm really bad at it most of the time. These are the artifacts I've collected along the way."
gravatar = "hello@heiber.im"
mainSections = "posts"
postsOnHomePage = 5
rss = true
showAllPostsOnHomePage = false
showProjectsList = true
show_updated = true
tagsOverview = true

[[params.social]]
link = "https://mastodon.social/@moritzheiber"
name = "mastodon"

[[params.social]]
link = "https://github.com/moritzheiber"
name = "github"

[[params.social]]
link = "hello+web@heiber.im"
name = "email"

[params.comments]
enabled = false

[[menu.main]]
identifier = "home"
name = "home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "about"
url = "/about"
weight = 2

[[menu.main]]
identifier = "media"
name = "media"
url = "/media"
weight = 3

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/posts"
weight = 4

[[menu.footer]]
identifier = "imprint"
name = "imprint"
top = false
url = "/imprint"
weight = 5

[taxonomies]
category = "categories"
tags = "tags"
