[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://social.heiber.im/.well-known/webfinger"
  status = 301
  force = true

[[redirects]]
  from = "/.well-known/host-meta"
  to = "https://social.heiber.im/.well-known/host-meta"
  status = 301
  force = true
